### ISSUE TITLE
v4固件下的小键盘，无法通过usb-hub连接电脑

### ISSUE THREAD

**Issue by louis16s** [yuan910715/3keys#1]
排除了type-c线的问题，同样的扩展坞，上一版的固件可以直接使用
v4固件的则没有反应

**Comment by yuan910715** [comment]
使用 USB A to C 数据线 还是 C to C 数据线？
不适用扩展坞可否正常连接？

> 排除了type-c线的问题，同样的扩展坞，上一版的固件可以直接使用 v4固件的则没有反应

**Comment by louis16s** [comment]
使用a 2 c，直连笔记本可用

Have a nice day
r祺
________________________________
发件人: MonsterYuan ***@***.***>
发送时间: Thursday, March 30, 2023 4:44:11 PM
收件人: yuan910715/3keys ***@***.***>
抄送: louis16s ***@***.***>; Author ***@***.***>
主题: Re: [yuan910715/3keys] v4固件下的小键盘，无法通过usb-hub连接电脑 (Issue #1)


使用 USB A to C 数据线 还是 C to C 数据线？
不适用扩展坞可否正常连接？

排除了type-c线的问题，同样的扩展坞，上一版的固件可以直接使用 v4固件的则没有反应

―

**Comment by yuan910715** [comment]
使用扩展坞连接后, web改键页能否连接设备？ https://topyuan.top/3key

**Comment by louis16s** [comment]
抱歉，打扰了
经过多次试验，现在成功通过hub连上了键盘
原因未知
给您带来不便，敬请谅解

Have a nice day
r祺
________________________________
发件人: MonsterYuan ***@***.***>
发送时间: Thursday, March 30, 2023 4:53:54 PM
收件人: yuan910715/3keys ***@***.***>
抄送: louis16s ***@***.***>; Author ***@***.***>
主题: Re: [yuan910715/3keys] v4固件下的小键盘，无法通过usb-hub连接电脑 (Issue #1)


使用扩展坞连接后, web改键页能否连接设备？ https://topyuan.top/3key

―

**Comment by yuan910715** [comment]
插上USB线后 需要等待2秒再操作键盘
如果刚插上就立刻按键 会导致键盘按键不可用，但此时改键可正常连接. 这个问题原因未知。怀疑是这个问题导致。

**Comment by yuan910715** [comment]
> 
V4.1已解决此问题
https://github.com/DeqingSun/ch55xduino/issues/132
