### ISSUE TITLE
HID按键2个问题？

### ISSUE THREAD

**Issue by wuqi716** [yuan910715/3keys#12]
1、请教楼主，XP,WIN7系统不装驱动都支持吗？

2、如果按键按下状态（一直按着），怎么能每1秒循环发送键值？请教楼主

**Comment by yuan910715** [comment]
WIN 7试过，键盘可用，改键需要安装USB CDC驱动，XP没有试过。
Keyboard_press和Keyboard_release分别为按键按下、释放方法，如果一直按着，操作系统会控制一直输出相应按键，如果想手动每隔1秒触发一次，延时控制就行。

**Comment by wuqi716** [comment]
收到，谢谢，改键需要安装USB CDC驱动意思是在电脑上安装，还是在Arduino里插入代码编译生成HEX程序？&nbsp;


吴先生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月26日(星期五) 上午10:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuan910715/3keys] HID按键2个问题？ (Issue #12)














 
WIN 7试过，键盘可用，改键需要安装USB CDC驱动，XP没有试过。
 Keyboard_press和Keyboard_release分别为按键按下、释放方法，如果一直按着，操作系统会控制一直输出相应按键，如果想手动每隔1秒触发一次，延时控制就行。

**Comment by yuan910715** [comment]
需要在WIN 7的PC上安装USB CDC驱动，否则可能不会识别USB串口设备，导致改键页面不能搜到设备

**Comment by wuqi716** [comment]
收到，谢谢，我试试


&nbsp;


吴先生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年4月26日(星期五) 上午10:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuan910715/3keys] HID按键2个问题？ (Issue #12)














 
需要在WIN 7的PC上安装USB CDC驱动，否则可能不会识别USB串口设备，导致改键页面不能搜到设备
