### ISSUE TITLE
关于换行符的问题

### ISSUE THREAD

**Issue by sanbrother** [yuan910715/3keys#14]
请问下，在网页上，可以在字符串后面添加换行符吗？
比如说HELLO\n，结果会把\n输出，而不是期待的换行

谢谢

**Comment by yuan910715** [comment]
已增加，请帮助测试

**Comment by sanbrother** [comment]
收到，非常感谢。测试后反馈结果

**Comment by sanbrother** [comment]
> 已增加，请帮助测试
确认完成，非常好用。您增加的回车选项真的方便，我原本以为会处理成转义符，那样还真挺麻烦。
感谢您开源的作品，太好用了

**Comment by sanbrother** [comment]
再次感谢
