### ISSUE TITLE
关于数字锁定，滚轮锁定和空格键的问题

### ISSUE THREAD

**Issue by Mr-ShiYi** [yuan910715/3keys#15]
你好，我在ch552的例程库文件里没有看见关于这三个按键，能告诉我是哪个对应这三个按键吗

**Comment by yuan910715** [comment]
Scroll Lock : 0xCF
Num Lock : 0xDB
空格键是ASCII码0x20

**Comment by Mr-ShiYi** [comment]
![4b71fdce3759dc9007e49790da502e84](https://github.com/user-attachments/assets/5782712c-73e2-4a25-8a87-af0a5fedbb00)
请问，怎么利用这个程序使用这些按键，直接用ascl码吗

**Comment by yuan910715** [comment]
参考Keyboard_press(0x20)

**Comment by Mr-ShiYi** [comment]
在那可以看正确的ASCLL码，我在网上搜的对应不上
