### ISSUE TITLE
关于模拟鼠标

### ISSUE THREAD

**Issue by BD3OOX** [yuan910715/3keys#16]
ok

**Comment by BD3OOX** [comment]
@ @ @

**Comment by yuan910715** [comment]
你好 没复现问题 请详细描述一下设置过程

**Comment by BD3OOX** [comment]
第一次:设置成 鼠标 长按按住鼠标,保存
第二次,鼠标 向上移动,保存
第三次,改回第一次的配置
这样就变成长按+移动了

**Comment by yuan910715** [comment]
已修复，请重新刷入7.0测试

**Comment by BD3OOX** [comment]
实际一直有个问题,没多问,github下载的hex固件,WCHISP都会提示hex转bin失败,从你网站下的没事,我自己编译的也没事
