### ISSUE TITLE
请教一下HID的问题

### ISSUE THREAD

**Issue by hanbingniao** [yuan910715/3keys#2]
你好！从deqingsun大大的issues看到了您，正好也是做类似的东西，然后看到那个cdc的项目是声明的HID键盘，但是我想用媒体键盘，但是对HID不太熟u，改了一下午，请教一下那个reportID要怎么改呀？现在合并完了虽然能编译但是按键用不了，看到您实现了，想请教一下，谢谢！

**Comment by yuan910715** [comment]
看下我的代码， 是CDC+多媒体键盘的。就是reportID要和desc里的对应就行

**Comment by hanbingniao** [comment]
仔细研究了一下，非常感谢！！
最近也在做ch552的小键盘，算是单片机初学，还有有很多不懂的哈哈哈
然后能在我的项目里用一下您的src的文件吗？谢谢！

**Comment by yuan910715** [comment]
> 

可以
