### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by Mr-ShiYi** [yuan910715/3keys#6]
请问，v5.1码源能发一下吗，我想改个连接名称

**Comment by Zylsjsp** [comment]
@yuan910715 看了一下commit记录 可以考虑去了解一下git的使用方法 本地git仓库修改了之后可以git push和GitHub同步 省去单独上传的麻烦了

命令行工具不好上手的话可以考虑一下vscode git插件 非常直观好用

**Comment by yuan910715** [comment]
5.1源码已上传。

> 请问，v5.1码源能发一下吗，我想改个连接名称

**Comment by yuan910715** [comment]
> @yuan910715 看了一下commit记录 可以考虑去了解一下git的使用方法 本地git仓库修改了之后可以git push和GitHub同步 省去单独上传的麻烦了
> 
> 命令行工具不好上手的话可以考虑一下vscode git插件 非常直观好用

公司的网络有限制，git push跑不了 我就直接web页面上传了。

**Comment by Mr-ShiYi** [comment]
好的，谢谢

**Comment by Mr-ShiYi** [comment]
> 5.1源码已上传。
> 
> > 请问，v5.1码源能发一下吗，我想改个连接名称

@yuan910715 请问0x0317和0x030e两个代码什么意思，我知道0x0316是改连接名称的
![微信截图_20230720110902](https://github.com/yuan910715/3keys/assets/133103605/0b6d1441-ef04-4445-91bf-0694c0d455e0)

**Comment by yuan910715** [comment]
> 

是CDC的描述信息 但windows不会显示

**Comment by Mr-ShiYi** [comment]
好的，谢谢，那我可以不管他，只改0316
