### ISSUE TITLE
dataflash数据存储问题

### ISSUE THREAD

**Issue by LUCA-5342** [yuan910715/3keys#7]
您好，我注意到CH552G芯片内置的dataflash只有128K，dedingsun的eeprom.h中也描述到if (addr >= 128) {
    return;
  }，看您的板子并没有增加外置存储，想请问您是如何做到eeprom读写到152地址的呢，是否能更多？
顺带一提，把鼠标加进来太棒了，可惜源码中并没有~

**Comment by yuan910715** [comment]
您好 纠正一下CH552G芯片内置的dataflash是128字节 不是128K  之前我没注意到 所以有大于128的 实际重新插拔USB线后这部分设置就丢失了-_-|| 
我把最新源码上传了 包含鼠标部分了。
现在保存设置很多项是按1字节保存 实际用不了这么多  改为按位拼接保存 会省一些空间。

**Comment by LUCA-5342** [comment]
感谢回答，之前就想做这个，但一直没有时间，最近抽空鼓捣了一下，结果需要近300字节的eeprom才够，查看报文发现128之后开始循环了，准备考虑一下按位拼接保存！
